### PR TITLE
User Data Partition update for find5

### PR DESCRIPTION
**Pull request by wolverine2k**
Adds the ability to increase the userdata partition for
find5 (16/32GB) models. The user gets to select the data
size that he would like to keep and press a button. Rest
of the process happens automagically. User can select
the data partition between 6GB and 10GB with default being
10GB. It is assumed that
1. ADB drivers are installed and is available in the path
2. Openrecovery TWRP is available and installed
3. mke2fs, tune2fs and mkdosfs are available in sbin
Troubleshooting and extra files can be downloaded from
http://forum.xda-developers.com/showpost.php?p=57638797&postcount=34

Packaging the files is a separate activity.

### CODE REVIEW

**Comment by wolverine2k** [comment]
Packaging the extra files needed to get the patch working is a separate activity. I can help out with that once the above is merged.

**Comment by wolverine2k** [comment]
Tested and working great both on Linux and Windows. Also updated to use QProcessEnvironment() instead of setenv() which works in Linux and Windows Environment.

**Comment by wolverine2k** [comment]
Hey jrizzoli,

Since you are the new owner for this repo, I have done a patch to increase the partition size of find5 in this tool. The tool works great and has already been verified. Check http://forum.xda-developers.com/showthread.php?t=2608337&page=12. Would be great if you can merge the pull request.

**Comment by wolverine2k** [comment]
Cool, travis passes on the linux build for this branch.

**Comment by jrizzoli** [comment]
I don't have time for this atm, fell free to push pull req

**Pull request merged**
